{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "state": "PUBLISHED",
    "cveId": "CVE-2024-31584",
    "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
    "assignerShortName": "mitre",
    "dateUpdated": "2024-06-04T17:37:14.649Z",
    "dateReserved": "2024-04-05T00:00:00",
    "datePublished": "2024-04-19T00:00:00"
  },
  "containers": {
    "cna": {
      "providerMetadata": {
        "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "shortName": "mitre",
        "dateUpdated": "2024-04-19T20:47:50.376803"
      },
      "descriptions": [
        {
          "lang": "en",
          "value": "Pytorch before v2.2.0 has an Out-of-bounds Read vulnerability via the component torch/csrc/jit/mobile/flatbuffer_loader.cpp."
        }
      ],
      "affected": [
        {
          "vendor": "n/a",
          "product": "n/a",
          "versions": [
            {
              "version": "n/a",
              "status": "affected"
            }
          ]
        }
      ],
      "references": [
        {
          "url": "https://github.com/pytorch/pytorch/commit/7c35874ad664e74c8e4252d67521f3986eadb0e6"
        },
        {
          "url": "https://github.com/pytorch/pytorch/blob/v2.1.2/torch/csrc/jit/mobile/flatbuffer_loader.cpp#L305"
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "type": "text",
              "lang": "en",
              "description": "n/a"
            }
          ]
        }
      ]
    },
    "adp": [
      {
        "metrics": [
          {
            "cvssV3_1": {
              "scope": "UNCHANGED",
              "version": "3.1",
              "baseScore": 5.5,
              "attackVector": "NETWORK",
              "baseSeverity": "MEDIUM",
              "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:L",
              "integrityImpact": "LOW",
              "userInteraction": "REQUIRED",
              "attackComplexity": "LOW",
              "availabilityImpact": "LOW",
              "privilegesRequired": "LOW",
              "confidentialityImpact": "LOW"
            }
          },
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2024-31584",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "no"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-04-22T14:17:54.215564Z"
              }
            }
          }
        ],
        "affected": [
          {
            "cpes": [
              "cpe:2.3:a:pytorchlightning:pytorch_lightning:*:*:*:*:*:python:*:*"
            ],
            "vendor": "pytorchlightning",
            "product": "pytorch_lightning",
            "versions": [
              {
                "status": "affected",
                "version": "2.2.0"
              }
            ],
            "defaultStatus": "unknown"
          }
        ],
        "problemTypes": [
          {
            "descriptions": [
              {
                "lang": "en",
                "type": "CWE",
                "cweId": "CWE-125",
                "description": "CWE-125 Out-of-bounds Read"
              }
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-04-22T14:15:15.699Z"
        },
        "title": "CISA ADP Vulnrichment"
      }
    ]
  }
}